#!/bin/bash

IP_ADDRESS=$(wget http://ipinfo.io/ip -qO -)
IP_LOC=$(geoiplookup $IP_ADDRESS | grep -oP -m 1 "( [A-Z]{2})")

if [[ "${IP_LOC}" != "" ]]; then
  echo "${IP_LOC}: "
  echo "${IP_LOC}: "
  echo ""
fi
