#!/bin/bash
# Based on https://aur.archlinux.org/packages/playerctl/

INSTANCE="spotify"

if [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
	i3-msg 'workspace 10:    ' > /dev/null
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
	i3-msg 'workspace 10:    ' > /dev/null
fi

if [[ "${INSTANCE}" != "" ]]; then
  ARGUMENTS="--player ${INSTANCE}"
fi

ICON_PLAY="➤"
ICON_PAUSE="Ⅱ"
ICON_STOP="≠"
CUR_ICON=""


PLAYER_STATUS=$(playerctl ${ARGUMENTS} status)
INFO_TITLE=$(playerctl ${ARGUMENTS} metadata title)
INFO_ALBUM=$(playerctl ${ARGUMENTS} metadata album)
INFO_ARTIST=$(playerctl ${ARGUMENTS} metadata artist)

if [[ "${PLAYER_STATUS}" = "Paused" ]]; then
	echo ""
	echo ""
	echo ""
	exit
elif [[ "${PLAYER_STATUS}" = "Playing" ]]; then
  CUR_ICON="${ICON_PLAY}"
else
  CUR_ICON="${ICON_STOP}"
fi

if [[ "${INFO_TITLE}" != "" ]] && [[ "${INFO_ARTIST}" != "(null)" ]]; then
  echo "${INFO_ARTIST} - ${INFO_TITLE}"
  echo "${INFO_ARTIST} - ${INFO_TITLE}"
fi
