#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	i3-msg 'workspace 11:    '
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
	/usr/share/wicd/daemon/autoconnect.py
fi


if [[ ! -d /sys/class/net/${INTERFACE}/wireless ]]; then
	echo "0%"
	echo "0%"
	echo "#C55D51"
	exit
fi	
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" == 'down' ]]; then
	echo "0%"
	echo "0%"
	echo "#C55D51"
	exit
fi	


#------------------------------------------------------------------------

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

echo $QUALITY% # full text
echo $QUALITY # short text

# color
if [[ $QUALITY -ge 80 ]]; then
    echo "#B8BB26"
elif [[ $QUALITY -lt 80 ]]; then
    echo "#FABD2F"
elif [[ $QUALITY -lt 60 ]]; then
    echo "#FE8019"
elif [[ $QUALITY -lt 40 ]]; then
	echo "#C55D51"
fi
