#!/bin/bash

ARGUMENTS="--player spotify"

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	playerctl ${ARGUMENTS} previous
fi

PLAYER_STATUS=$(playerctl ${ARGUMENTS} status)

if [[ "${PLAYER_STATUS}" != "Paused" ]] && [[ "${PLAYER_STATUS}" != "Playing" ]]; then
	echo ""
	echo ""
	echo ""
	exit
fi

if [[ "${PLAYER_STATUS}" = "Playing" ]]; then
	echo ""
	echo ""
	echo ""
else
	echo " "
	echo " "
	echo ""
fi

